name: community-site-dev

channels:
  - conda-forge

dependencies:
  - python=3.12

  # GitHub tooling
  - gh
  - jupyterlab-git

  # In-browser quarto editing
  - jupyter-server-proxy
  - code-server

  # Quarto build Python dependencies

  # Jupyter extensions
  - pip
  - pip:
      - jupyterlab-quarto
      - jupyter-code-server
