#!/usr/bin/env bash

# Bash debugging settings
set -euxo pipefail

######################
### Install Quarto ###
######################

QUARTO_VERSION="1.7.34"
INSTALL_PREFIX="${CONDA_DIR:-/srv/conda}"
QUARTO_DIR="${INSTALL_PREFIX}/opt/quarto-${QUARTO_VERSION}"
QUARTO_ARCHIVE="/tmp/quarto.tar.gz"

# Download Quarto
curl \
  --fail \
  --silent \
  --show-error \
  --location \
  "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.tar.gz" \
  --output "${QUARTO_ARCHIVE}"

# Extract Quarto archive
mkdir -p "${QUARTO_DIR}"
tar \
  --extract \
  --gzip \
  --file "${QUARTO_ARCHIVE}" \
  --directory "${QUARTO_DIR}" \
  --strip-components=1

# Install Quarto
ln -sfn \
  "${QUARTO_DIR}/bin/quarto" \
  "${INSTALL_PREFIX}/bin/quarto"

# Clean up
rm -f "${QUARTO_ARCHIVE}"

#########################
### Configure Jupyter ###
#########################

JUPYTER_ENV_CONFIG="${CONDA_DIR}/envs/notebook/etc/jupyter"

mkdir -p "$JUPYTER_ENV_CONFIG"
cp binder/jupyter_server_config.py \
  "$JUPYTER_ENV_CONFIG/jupyter_server_config.py"