name: Build authoring image

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "binder/**"
      - ".github/workflows/build-image.yml"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/eculler/community-site-dev

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Build and publish repo2docker image
        id: repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ${{ vars.REGISTRY }}
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
