on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore: "binder/**"

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eculler/community-site-dev:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
